pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/leonardotorre18/jenkins.git'
            }
        }
        stage('Run Application') {
            steps {
                sh 'npm install'
                sh 'npm start'
            }
        }
    }
}