pipeline {
    agent any

    tools {
        nodejs 'node'
    }

    stages {
        stage('Install') {
            steps {
                git branch: 'main', url: 'https://github.com/leonardotorre18/jenkins.git'
                dir('backend') {
                    sh 'npm ci'
                }
            }
        }
        stage('Building') {
            steps {
                dir('backend') {
                    sh 'npm run build'
                }
            }
        }
    }
}